# Generated by Django 3.1.13 on 2021-12-01 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updated at')),
                ('disabled_at', models.DateTimeField(blank=True, null=True, verbose_name='Disabled at')),
                ('status', models.IntegerField(choices=[(1, 'active'), (2, 'disabled'), (3, 'done')], default=1, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
            },
        ),
    ]
