# Generated by Django 3.1.13 on 2021-12-01 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.JSONField(verbose_name='Answers')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='activity.activitymodel', verbose_name='Activity')),
            ],
            options={
                'verbose_name': 'Survey',
                'verbose_name_plural': 'Surveys',
            },
        ),
    ]
