# Generated by Django 3.1.13 on 2021-12-01 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveymodel',
            old_name='description',
            new_name='answers',
        ),
    ]
