# Generated by Django 3.2.9 on 2021-11-29 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.DateTimeField(auto_now_add=True, verbose_name='Schedule')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated at')),
                ('status', models.IntegerField(choices=[(1, 'active'), (2, 'disabled'), (3, 'done')], default=1, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='PropertyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated at')),
                ('disabled_at', models.DateTimeField(auto_now_add=True, verbose_name='Disabled at')),
                ('status', models.IntegerField(choices=[(1, 'active'), (2, 'disabled'), (3, 'done')], default=1, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='SurveyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.JSONField(verbose_name='Answers')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.activitymodel', verbose_name='Activity')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.AddField(
            model_name='activitymodel',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.propertymodel', verbose_name='Property'),
        ),
    ]
