# Generated by Django 3.2.9 on 2021-11-30 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveymodel',
            options={'verbose_name': 'Survey', 'verbose_name_plural': 'Surveys'},
        ),
        migrations.AlterField(
            model_name='activitymodel',
            name='schedule',
            field=models.DateTimeField(verbose_name='Schedule'),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='disabled_at',
            field=models.DateTimeField(verbose_name='Disabled at'),
        ),
    ]
