# Generated by Django 3.2.9 on 2021-11-30 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20211129_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitymodel',
            name='updated_at',
            field=models.DateTimeField(verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='disabled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Disabled at'),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='updated_at',
            field=models.DateTimeField(verbose_name='Updated at'),
        ),
    ]
