# Generated by Django 3.1.13 on 2021-11-30 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_auto_20211129_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitymodel',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Updated at'),
        ),
    ]
