# Generated by Django 3.1.13 on 2021-11-30 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_auto_20211129_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitymodel',
            name='status',
            field=models.IntegerField(choices=[(1, 'active'), (2, 'disabled'), (3, 'done'), (4, 'canceled')], default=1, verbose_name='Status'),
        ),
    ]
