# Generated by Django 3.1.13 on 2021-11-30 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_auto_20211130_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveymodel',
            name='activity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='business.activitymodel', verbose_name='Activity'),
        ),
    ]
